name: Release Build

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Get version
        id: get_version
        run: |
          echo "VERSION=$(date +'v%Y.%m.%d-%H%M')" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o bin/undine-windows-amd64.exe
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/undine-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o bin/undine-darwin-amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          files: |
            bin/undine-windows-amd64.exe
            bin/undine-linux-amd64
            bin/undine-darwin-amd64
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}